# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thank you for opening this issue!
    I have applied labels based on keywords in the title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thank you for the contribution!
    I have applied labels based on keywords in the title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'bug':
    include:
      - '\bBug:|/bug\b'
    exclude: []
  'feature':
    include:
      - '\bFeat:|/feature\b:'
    exclude: []
  'WIP':
    include:
      - '\b[WIP]|/draft\b'
